# Generated by Django 4.0.10 on 2023-08-07 16:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c91f81e0-6a0a-43c0-9f50-ca0952921f1e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
